# Generated by Django 4.2.7 on 2026-04-22 11:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'db_table': 'asset_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_id', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Asset Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('make', models.CharField(blank=True, max_length=100, null=True, verbose_name='Make/Brand')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('serial_number', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-_]+$', 'Only alphanumeric characters, hyphens and underscores allowed')], verbose_name='Serial Number')),
                ('ownership_type', models.CharField(choices=[('owned', 'Fully Owned'), ('financed', 'Financed'), ('leased', 'Leased'), ('joint', 'Joint Ownership')], default='owned', max_length=20, verbose_name='Ownership Type')),
                ('ownership_proof', models.FileField(blank=True, null=True, upload_to='collateral/ownership_proof/', verbose_name='Proof of Ownership')),
                ('condition', models.CharField(choices=[('new', '🆕 New'), ('excellent', '⭐ Excellent'), ('very_good', '✅ Very Good'), ('good', '👍 Good'), ('fair', '⚠️ Fair'), ('poor', '🔻 Poor'), ('damaged', '💔 Damaged')], default='good', max_length=20, verbose_name='Condition')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated Value (ZMW)')),
                ('appraised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Appraised Value (ZMW)')),
                ('loan_to_value_ratio', models.DecimalField(decimal_places=2, default=70, help_text='Percentage of value that can be lent', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='LTV Ratio (%)')),
                ('storage_location', models.CharField(max_length=200, verbose_name='Storage Location')),
                ('storage_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section')),
                ('storage_shelf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shelf/Rack')),
                ('storage_condition', models.TextField(blank=True, null=True, verbose_name='Storage Conditions')),
                ('primary_photo', models.ImageField(blank=True, null=True, upload_to='collateral/photos/', verbose_name='Primary Photo')),
                ('additional_photos', models.ImageField(blank=True, null=True, upload_to='collateral/additional_photos/', verbose_name='Additional Photos')),
                ('certificate_of_ownership', models.FileField(blank=True, null=True, upload_to='collateral/certificates/', verbose_name='Certificate of Ownership')),
                ('valuation_certificate', models.FileField(blank=True, null=True, upload_to='collateral/valuations/', verbose_name='Valuation Certificate')),
                ('insurance_certificate', models.FileField(blank=True, null=True, upload_to='collateral/insurance/', verbose_name='Insurance Certificate')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='collateral/qrcodes/', verbose_name='QR Code')),
                ('verification_status', models.CharField(choices=[('pending', '⏳ Pending'), ('verified', '✅ Verified'), ('rejected', '❌ Rejected'), ('requires_review', '⚠️ Requires Review')], default='pending', max_length=20, verbose_name='Verification Status')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('verification_notes', models.TextField(blank=True, null=True, verbose_name='Verification Notes')),
                ('is_insured', models.BooleanField(default=False, verbose_name='Is Insured?')),
                ('insurance_provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Insurance Provider')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Policy Number')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='Insurance Expiry Date')),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Insured Value (ZMW)')),
                ('status', models.CharField(choices=[('available', '🟢 Available'), ('pledged', '🔵 Pledged'), ('seized', '🔴 Seized'), ('sold', '💸 Sold'), ('released', '⬜ Released'), ('pending', '🟡 Pending Review')], default='available', max_length=20, verbose_name='Status')),
                ('is_seized', models.BooleanField(default=False, verbose_name='Is Seized?')),
                ('seized_date', models.DateTimeField(blank=True, null=True, verbose_name='Seized Date')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Release Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_physical_check', models.DateField(blank=True, null=True, verbose_name='Last Physical Check')),
                ('next_physical_check', models.DateField(blank=True, null=True, verbose_name='Next Physical Check')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for easy searching', max_length=500, null=True, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Collateral',
                'verbose_name_plural': 'Collaterals',
                'db_table': 'collateral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollateralInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('initial', '📋 Initial'), ('quarterly', '📅 Quarterly'), ('annual', '📆 Annual'), ('special', '🔍 Special'), ('release', '✅ Pre-release'), ('random', '🎲 Random')], max_length=20, verbose_name='Inspection Type')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now, verbose_name='Inspection Date')),
                ('condition', models.CharField(choices=[('new', '🆕 New'), ('excellent', '⭐ Excellent'), ('very_good', '✅ Very Good'), ('good', '👍 Good'), ('fair', '⚠️ Fair'), ('poor', '🔻 Poor'), ('damaged', '💔 Damaged')], max_length=20, verbose_name='Condition Found')),
                ('notes', models.TextField(verbose_name='Inspection Notes')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='collateral/inspections/', verbose_name='Inspection Photos')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Recommendations')),
                ('requires_action', models.BooleanField(default=False, verbose_name='Requires Action')),
                ('action_taken', models.BooleanField(default=False, verbose_name='Action Taken')),
                ('action_notes', models.TextField(blank=True, null=True, verbose_name='Action Notes')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Next Inspection Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collateral Inspection',
                'verbose_name_plural': 'Collateral Inspections',
                'db_table': 'collateral_inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='CollateralMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('received', '📥 Received'), ('moved', '🚚 Moved'), ('released', '📤 Released'), ('seized', '🔒 Seized'), ('sold', '💸 Sold'), ('transferred', '🔄 Transferred'), ('returned', '↩️ Returned')], max_length=20, verbose_name='Movement Type')),
                ('from_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='From Location')),
                ('to_location', models.CharField(max_length=200, verbose_name='To Location')),
                ('reason', models.TextField(verbose_name='Reason for Movement')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Movement Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='Authorization Date')),
            ],
            options={
                'verbose_name': 'Collateral Movement',
                'verbose_name_plural': 'Collateral Movements',
                'db_table': 'collateral_movements',
                'ordering': ['-movement_date'],
            },
        ),
    ]
