# Generated by Django 4.2.7 on 2026-04-22 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collateral', '0001_initial'),
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralmovement',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_movements', to=settings.AUTH_USER_MODEL, verbose_name='Authorized By'),
        ),
        migrations.AddField(
            model_name='collateralmovement',
            name='collateral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='collateral.collateral', verbose_name='Collateral'),
        ),
        migrations.AddField(
            model_name='collateralmovement',
            name='moved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Moved By'),
        ),
        migrations.AddField(
            model_name='collateralinspection',
            name='collateral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='collateral.collateral', verbose_name='Collateral'),
        ),
        migrations.AddField(
            model_name='collateralinspection',
            name='inspected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Inspected By'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaterals', to='collateral.assettype', verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaterals', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='current_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaterals', to='loans.loan', verbose_name='Associated Loan'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='seized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seized_collaterals', to=settings.AUTH_USER_MODEL, verbose_name='Seized By'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_collaterals', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddIndex(
            model_name='collateralmovement',
            index=models.Index(fields=['collateral', '-movement_date'], name='collateral__collate_4d5011_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralmovement',
            index=models.Index(fields=['movement_type'], name='collateral__movemen_e70a78_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralmovement',
            index=models.Index(fields=['movement_date'], name='collateral__movemen_32bdae_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralinspection',
            index=models.Index(fields=['collateral', '-inspection_date'], name='collateral__collate_aada08_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralinspection',
            index=models.Index(fields=['inspection_type'], name='collateral__inspect_11e602_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['collateral_id'], name='collateral_collate_6325cc_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['serial_number'], name='collateral_serial__07b9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['client', 'status'], name='collateral_client__44bf06_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['verification_status'], name='collateral_verific_ad66ba_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['created_at'], name='collateral_created_e7e95a_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['asset_type'], name='collateral_asset_t_9853f6_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['condition'], name='collateral_conditi_87781c_idx'),
        ),
    ]
