# Generated by Django 4.2.7 on 2026-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='status',
            field=models.CharField(choices=[('available', '🟢 Available'), ('pledged', '🔵 Pledged'), ('seized', '🔴 Seized'), ('sold', '💸 Sold'), ('released', '⬜ Released'), ('pending', '🟡 Pending Review'), ('assigned', 'Assigned')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
