# Generated by Django 4.2.7 on 2026-04-22 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('nrc', models.CharField(help_text='Format: 123456/12/1', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}/\\d{2}/\\d$', 'Invalid NRC format. Use: 123456/12/1')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?260\\d{9}$|^0\\d{9}$', 'Invalid phone number. Use: +260977123456 or 0977123456')])),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('physical_address', models.TextField()),
                ('postal_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='Zambia', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('business', 'Business Owner'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], default='employed', max_length=20)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employment_start_date', models.DateField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nrc_photo', models.ImageField(help_text='Upload NRC photo', upload_to='clients/nrc/')),
                ('client_photo', models.ImageField(help_text='Upload client photo', upload_to='clients/photos/')),
                ('proof_of_residence', models.FileField(blank=True, null=True, upload_to='clients/proof_of_residence/')),
                ('proof_of_income', models.FileField(blank=True, null=True, upload_to='clients/proof_of_income/')),
                ('kyc_verified', models.BooleanField(default=False)),
                ('kyc_verified_date', models.DateTimeField(blank=True, null=True)),
                ('risk_rating', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=10)),
                ('credit_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('risk_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted'), ('pending', 'Pending Verification')], default='pending', max_length=20)),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
                ('blacklisted_date', models.DateTimeField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('general_notes', models.TextField(blank=True, help_text='General notes about the client', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('property', 'Property/Land'), ('equipment', 'Equipment/Machinery'), ('livestock', 'Livestock'), ('electronics', 'Electronics'), ('jewelry', 'Jewelry'), ('business', 'Business'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('proof_of_ownership', models.FileField(blank=True, null=True, upload_to='client_assets/proof/')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='client_assets/photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_assets',
                'ordering': ['-estimated_value'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('physical_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20)),
                ('relationship_years', models.IntegerField(default=0)),
                ('nrc_photo', models.ImageField(upload_to='guarantors/nrc/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guarantors/photos/')),
                ('proof_of_residence', models.FileField(blank=True, null=True, upload_to='guarantors/proof_of_residence/')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='clients.client')),
            ],
            options={
                'db_table': 'guarantors',
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_type', models.CharField(default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client')),
            ],
            options={
                'db_table': 'client_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
