# Generated by Django 4.2.7 on 2026-04-22 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientasset',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientasset',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['nrc'], name='guarantors_nrc_52d2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['phone_number'], name='guarantors_phone_n_42e395_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nrc'], name='clients_nrc_f3d0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_number'], name='clients_phone_n_1a9953_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['first_name', 'last_name'], name='clients_first_n_3d2859_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_status_98ee60_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['risk_rating'], name='clients_risk_ra_fcba56_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['registration_date'], name='clients_registr_b7a184_idx'),
        ),
    ]
