# Generated by Django 4.2.7 on 2026-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_bid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('scheduled_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('final_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_balance_at_auction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('surplus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deficit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auction_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('legal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('winner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('winner_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('winner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_notice', models.FileField(blank=True, null=True, upload_to='auction/legal_notices/')),
                ('auction_certificate', models.FileField(blank=True, null=True, upload_to='auction/certificates/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auctions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.CharField(max_length=200)),
                ('bidder_contact', models.CharField(max_length=50)),
                ('bidder_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('is_winning_bid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auction_bids',
                'ordering': ['-amount', '-bid_time'],
            },
        ),
        migrations.CreateModel(
            name='DefaultNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('days_overdue', models.IntegerField()),
                ('notice_date', models.DateField(auto_now_add=True)),
                ('response_deadline', models.DateField()),
                ('is_responded', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True, null=True)),
                ('legal_action_taken', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'default_notices',
                'ordering': ['-notice_date'],
            },
        ),
    ]
