# Generated by Django 6.0.4 on 2026-05-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        ('collateral', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='collateral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='collateral.collateral'),
        ),
        migrations.AddField(
            model_name='auction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auction'),
        ),
        migrations.AddField(
            model_name='defaultnotice',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_notices', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['auction_id'], name='auctions_auction_1618ec_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status'], name='auctions_status_12e6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['scheduled_date'], name='auctions_schedul_9ec5ff_idx'),
        ),
    ]
