# Generated by Django 4.2.7 on 2026-04-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate percentage', max_digits=5)),
                ('interest_period', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly')], default='week', max_length=10)),
                ('duration_weeks', models.IntegerField(help_text='Loan duration in weeks')),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_payback', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weekly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected'), ('restructured', 'Restructured')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the loan', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='loans.loan')),
            ],
            options={
                'db_table': 'repayment_schedules',
                'ordering': ['due_date'],
            },
        ),
    ]
