# Generated by Django 6.0.4 on 2026-05-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('collateral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate percentage', max_digits=5)),
                ('interest_period', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly')], default='week', max_length=10)),
                ('duration_weeks', models.IntegerField(help_text='Loan duration in weeks')),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_payback', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weekly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected'), ('restructured', 'Restructured')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the loan', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('late_payment_count', models.IntegerField(default=0, help_text='Number of late payments')),
                ('late_fee_total', models.DecimalField(decimal_places=2, default=0, help_text='Total late fees accumulated', max_digits=10)),
                ('last_late_fee_applied', models.DateTimeField(blank=True, help_text='When the last late fee was applied', null=True)),
                ('penalty_interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Additional penalty interest', max_digits=5)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance', max_digits=15)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='clients.client')),
                ('collateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='collateral.collateral')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('agreement_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='loan_agreements/')),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('borrower_signed', models.BooleanField(default=False)),
                ('borrower_signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/borrower/')),
                ('borrower_signed_at', models.DateTimeField(blank=True, null=True)),
                ('borrower_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('lender_signed', models.BooleanField(default=False)),
                ('lender_signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/lender/')),
                ('lender_signed_at', models.DateTimeField(blank=True, null=True)),
                ('lender_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_signatures', to=settings.AUTH_USER_MODEL)),
                ('lender_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lender_signatures', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='loans.loan')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_agreements',
                'ordering': ['-agreement_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, help_text='Late fee applied', max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, help_text='Expected amount + late fee', max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='loans.loan')),
            ],
            options={
                'db_table': 'repayment_schedules',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_id'], name='loans_loan_id_413fca_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client', 'status'], name='loans_client__fdc042_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['start_date'], name='loans_start_d_5ed714_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_status_9049a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repaymentschedule',
            unique_together={('loan', 'week_number')},
        ),
    ]
