# Generated by Django 6.0.4 on 2026-04-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('agreement_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='loan_agreements/')),
                ('signed_by_client', models.BooleanField(default=False)),
                ('signed_by_officer', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_agreements',
                'ordering': ['-agreement_date'],
            },
        ),
    ]
