# Generated by Django 6.0.4 on 2026-04-23 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanagreement_signature_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanagreement',
            options={'ordering': ['-agreement_date'], 'verbose_name': 'Loan Agreement', 'verbose_name_plural': 'Loan Agreements'},
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanagreement',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_agreements', to=settings.AUTH_USER_MODEL),
        ),
    ]
