# Generated by Django 6.0.4 on 2026-04-23 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loanagreement_options_loanagreement_signed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanagreement',
            options={'ordering': ['-agreement_date']},
        ),
        migrations.RenameField(
            model_name='loanagreement',
            old_name='signed_by_client',
            new_name='borrower_signed',
        ),
        migrations.RenameField(
            model_name='loanagreement',
            old_name='signed_by_officer',
            new_name='lender_signed',
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='borrower_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='borrower_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/borrower/'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='borrower_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='borrower_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='lender_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='lender_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/lender/'),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='lender_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='lender_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lender_signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
