# Generated by Django 6.0.4 on 2026-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanagreement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance', max_digits=15),
        ),
    ]
