# Generated by Django 6.0.4 on 2026-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loan_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_late_fee_applied',
            field=models.DateTimeField(blank=True, help_text='When the last late fee was applied', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='late_fee_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total late fees accumulated', max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='late_payment_count',
            field=models.IntegerField(default=0, help_text='Number of late payments'),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional penalty interest', max_digits=5),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late fee applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected amount + late fee', max_digits=12),
            preserve_default=False,
        ),
    ]
