# Generated by Django 6.0.4 on 2026-05-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('payment_received', '💰 Payment Received'), ('payment_approved', '✅ Payment Approved'), ('payment_rejected', '❌ Payment Rejected'), ('payment_reminder', '⏰ Payment Reminder'), ('loan_approved', '✅ Loan Approved'), ('loan_rejected', '❌ Loan Rejected'), ('loan_disbursed', '💸 Loan Disbursed'), ('loan_due', '📅 Loan Due'), ('loan_overdue', '⚠️ Loan Overdue'), ('collateral_due', '🏦 Collateral Due'), ('late_payment', '⚠️ Late Payment Warning'), ('account_activity', '👤 Account Activity'), ('system', '🖥️ System Notification'), ('reminder', '🔔 Reminder'), ('alert', '🚨 Alert'), ('info', 'ℹ️ Information'), ('promotion', '🎉 Promotion')], default='info', max_length=30)),
                ('priority', models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🟠 High'), ('urgent', '🔴 Urgent')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('whatsapp_notifications', models.BooleanField(default=False)),
                ('notify_payment', models.BooleanField(default=True)),
                ('notify_loan', models.BooleanField(default=True)),
                ('notify_reminder', models.BooleanField(default=True)),
                ('notify_alert', models.BooleanField(default=True)),
                ('notify_promotion', models.BooleanField(default=False)),
                ('notify_system', models.BooleanField(default=True)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('payment_received', '💰 Payment Received'), ('payment_approved', '✅ Payment Approved'), ('payment_rejected', '❌ Payment Rejected'), ('payment_reminder', '⏰ Payment Reminder'), ('loan_approved', '✅ Loan Approved'), ('loan_rejected', '❌ Loan Rejected'), ('loan_disbursed', '💸 Loan Disbursed'), ('loan_due', '📅 Loan Due'), ('loan_overdue', '⚠️ Loan Overdue'), ('collateral_due', '🏦 Collateral Due'), ('late_payment', '⚠️ Late Payment Warning'), ('account_activity', '👤 Account Activity'), ('system', '🖥️ System Notification'), ('reminder', '🔔 Reminder'), ('alert', '🚨 Alert'), ('info', 'ℹ️ Information'), ('promotion', '🎉 Promotion')], default='info', max_length=30)),
                ('priority', models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🟠 High'), ('urgent', '🔴 Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('action_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('action_button_link', models.CharField(blank=True, max_length=500, null=True)),
                ('related_payment_id', models.IntegerField(blank=True, null=True)),
                ('related_loan_id', models.IntegerField(blank=True, null=True)),
                ('related_client_id', models.IntegerField(blank=True, null=True)),
                ('related_collateral_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
