# Generated by Django 6.0.4 on 2026-04-24 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('whatsapp_notifications', models.BooleanField(default=False)),
                ('notify_payment', models.BooleanField(default=True)),
                ('notify_loan', models.BooleanField(default=True)),
                ('notify_reminder', models.BooleanField(default=True)),
                ('notify_alert', models.BooleanField(default=True)),
                ('notify_promotion', models.BooleanField(default=False)),
                ('notify_system', models.BooleanField(default=True)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='action_button_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_collateral_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_loan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_payment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='priority',
            field=models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🟠 High'), ('urgent', '🔴 Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_received', '💰 Payment Received'), ('payment_approved', '✅ Payment Approved'), ('payment_rejected', '❌ Payment Rejected'), ('payment_reminder', '⏰ Payment Reminder'), ('loan_approved', '✅ Loan Approved'), ('loan_rejected', '❌ Loan Rejected'), ('loan_disbursed', '💸 Loan Disbursed'), ('loan_due', '📅 Loan Due'), ('loan_overdue', '⚠️ Loan Overdue'), ('collateral_due', '🏦 Collateral Due'), ('late_payment', '⚠️ Late Payment Warning'), ('account_activity', '👤 Account Activity'), ('system', '🖥️ System Notification'), ('reminder', '🔔 Reminder'), ('alert', '🚨 Alert'), ('info', 'ℹ️ Information'), ('promotion', '🎉 Promotion')], default='info', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🟠 High'), ('urgent', '🔴 Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('payment_received', '💰 Payment Received'), ('payment_approved', '✅ Payment Approved'), ('payment_rejected', '❌ Payment Rejected'), ('payment_reminder', '⏰ Payment Reminder'), ('loan_approved', '✅ Loan Approved'), ('loan_rejected', '❌ Loan Rejected'), ('loan_disbursed', '💸 Loan Disbursed'), ('loan_due', '📅 Loan Due'), ('loan_overdue', '⚠️ Loan Overdue'), ('collateral_due', '🏦 Collateral Due'), ('late_payment', '⚠️ Late Payment Warning'), ('account_activity', '👤 Account Activity'), ('system', '🖥️ System Notification'), ('reminder', '🔔 Reminder'), ('alert', '🚨 Alert'), ('info', 'ℹ️ Information'), ('promotion', '🎉 Promotion')], default='info', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
